<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 13px; color: #1f2937; line-height: 1.6; }
    .page { padding: 40px 48px; }

    /* Header */
    .header { border-bottom: 2px solid #4f46e5; padding-bottom: 16px; margin-bottom: 24px; }
    .title { font-size: 22px; font-weight: bold; color: #111827; }
    .meta { margin-top: 6px; font-size: 11px; color: #6b7280; }
    .badge { display: inline-block; padding: 2px 10px; border-radius: 9999px; font-size: 11px; font-weight: 600; text-transform: capitalize; }
    .badge-completed { background: #d1fae5; color: #065f46; }
    .badge-failed    { background: #fee2e2; color: #991b1b; }
    .badge-pending   { background: #f3f4f6; color: #4b5563; }

    /* Sections */
    .section { margin-bottom: 28px; }
    .section-title { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #6b7280; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; margin-bottom: 12px; }

    /* Summary */
    .summary-text { color: #374151; }
    .key-points { margin-top: 10px; }
    .key-point { display: flex; gap: 8px; margin-bottom: 5px; }
    .dot { width: 6px; height: 6px; background: #4f46e5; border-radius: 50%; margin-top: 7px; flex-shrink: 0; }

    /* Todos */
    .todo-row { display: flex; justify-content: space-between; align-items: flex-start; padding: 8px 0; border-bottom: 1px solid #f3f4f6; }
    .todo-title { font-weight: 600; }
    .todo-desc { font-size: 11px; color: #6b7280; margin-top: 2px; }
    .todo-assignee { font-size: 11px; color: #4f46e5; margin-top: 2px; }
    .todo-status { font-size: 11px; padding: 2px 8px; border-radius: 9999px; white-space: nowrap; }
    .todo-pending    { background: #f3f4f6; color: #4b5563; }
    .todo-completed  { background: #d1fae5; color: #065f46; }
    .todo-in_progress { background: #dbeafe; color: #1e40af; }

    /* Transcript */
    .transcript { white-space: pre-wrap; font-size: 12px; color: #374151; background: #f9fafb; padding: 12px; border-radius: 4px; max-height: 400px; overflow: hidden; }

    /* Footer */
    .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; text-align: center; }
</style>
</head>
<body>
<div class="page">

    {{-- Header --}}
    <div class="header">
        <div class="title">{{ $meeting->title }}</div>
        <div class="meta">
            {{ $meeting->created_at->format('d M Y') }}
            @if($meeting->description)
                &nbsp;·&nbsp; {{ $meeting->description }}
            @endif
            &nbsp;&nbsp;
            <span class="badge badge-{{ $meeting->status }}">{{ $meeting->status }}</span>
        </div>
    </div>

    {{-- AI Summary --}}
    @if($meeting->aiSummary)
    <div class="section">
        <div class="section-title">AI Summary</div>
        <div class="summary-text">{{ $meeting->aiSummary->summary }}</div>

        @if($meeting->aiSummary->key_points && count($meeting->aiSummary->key_points) > 0)
        <div class="key-points">
            @foreach($meeting->aiSummary->key_points as $point)
            <div class="key-point">
                <div class="dot"></div>
                <div>{{ $point }}</div>
            </div>
            @endforeach
        </div>
        @endif
    </div>
    @endif

    {{-- Action Items --}}
    @if($meeting->todoItems && $meeting->todoItems->count() > 0)
    <div class="section">
        <div class="section-title">Action Items ({{ $meeting->todoItems->count() }})</div>
        @foreach($meeting->todoItems as $todo)
        <div class="todo-row">
            <div>
                <div class="todo-title">{{ $todo->title }}</div>
                @if($todo->description)
                    <div class="todo-desc">{{ $todo->description }}</div>
                @endif
                @if($todo->assignee)
                    <div class="todo-assignee">→ {{ $todo->assignee->name }}</div>
                @endif
            </div>
            <span class="todo-status todo-{{ $todo->status }}">{{ str_replace('_', ' ', $todo->status) }}</span>
        </div>
        @endforeach
    </div>
    @endif

    {{-- Transcript --}}
    @if($meeting->transcript)
    <div class="section">
        <div class="section-title">Transcript</div>
        <div class="transcript">{{ $meeting->transcript->content }}</div>
    </div>
    @endif

    <div class="footer">
        Generated by Meeting AI Platform · {{ now()->format('d M Y, H:i') }}
    </div>

</div>
</body>
</html>
